[build]
command = "CI= npm run build"
publish = "build"

[[redirects]]
  from = "/satellites/static/*"
  to = "/static/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
